[theme]
primaryColor = "#3B82F6"
backgroundColor = "#F8FAFC"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#0F172A"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
